( Henry Face gforth Raspberry Pi test harness)
( Dry-run is the default. Use REAL-GPIO to drive hardware.)
( Edit the GPIO constants before using REAL-GPIO on a live face.)
( The Raspberry Pi pin map can be set up later when wiring is ready.)
( Recommended wiring for TB6612FNG bring-up:)
( BCM17 -> AIN1  BCM27 -> AIN2  for eyes motor direction)
( BCM22 -> BIN1  BCM23 -> BIN2  for mouth motor direction)
( BCM24 -> STBY  shared driver enable)
( Tie PWMA and PWMB high for full-on drive in this harness.)
( Connect A01/A02 to eyes motor, B01/B02 to mouth motor.)
( VCC to Pi 3V3 logic, VM to motor supply, grounds common.)

DECIMAL

( Sample BCM GPIO map for bench wiring)
17 CONSTANT EYES-IN1-GPIO
27 CONSTANT EYES-IN2-GPIO
22 CONSTANT MOUTH-IN1-GPIO
23 CONSTANT MOUTH-IN2-GPIO
24 CONSTANT STBY-GPIO

250 VARIABLE BLINK-RATE-MS
250 VARIABLE BLINK-DELAY-MS
140 VARIABLE MOUTH-RATE-MS
120 VARIABLE MOUTH-DELAY-MS

VARIABLE GPIO-DRY-RUN
-1 GPIO-DRY-RUN !

-1 CONSTANT USE-SOFTWARE-PWM

: DRY-GPIO ( --) -1 GPIO-DRY-RUN ! ;
: REAL-GPIO ( --) 0 GPIO-DRY-RUN ! ;
: MS-WAIT ( N --) MS ;
: CLAMP0 ( N -- N') DUP 0< IF DROP 0 THEN ;
: U>STR ( U -- C-ADDR U) 0 <# #S #> ;
: CMD-RESET ( --) 0 PAD C! ;
: CMD-SETUP ( C-ADDR U --) PAD PLACE ;
: CMD-APPEND ( C-ADDR U --) PAD +PLACE ;
: RUN-CMD ( --)
  GPIO-DRY-RUN @ IF PAD COUNT TYPE CR ELSE PAD COUNT SYSTEM THEN
;

: PINCTRL-SET { PIN MODE-ADDR MODE-U -- }
  CMD-RESET
  S" pinctrl set " CMD-SETUP
  PIN U>STR CMD-APPEND
  S"  " CMD-APPEND
  MODE-ADDR MODE-U CMD-APPEND
  RUN-CMD
;

: GPIO-OUT ( PIN --) S" op" PINCTRL-SET ;
: GPIO-HIGH ( PIN --) S" dh" PINCTRL-SET ;
: GPIO-LOW ( PIN --) S" dl" PINCTRL-SET ;

( Henry Face PWM)
: TB6612-STBY-ON ( --) STBY-GPIO GPIO-HIGH ;
: TB6612-STBY-OFF ( --) STBY-GPIO GPIO-LOW ;
: EYES-PWM-ON ( --)
  USE-SOFTWARE-PWM 0< IF EXIT THEN
;
: EYES-PWM-OFF ( --)
  USE-SOFTWARE-PWM 0< IF EXIT THEN
;
: MOUTH-PWM-ON ( --)
  USE-SOFTWARE-PWM 0< IF EXIT THEN
;
: MOUTH-PWM-OFF ( --)
  USE-SOFTWARE-PWM 0< IF EXIT THEN
;

( Henry Face Pins)
: EYES-IN1-HIGH ( --) EYES-IN1-GPIO GPIO-HIGH ;
: EYES-IN1-LOW ( --) EYES-IN1-GPIO GPIO-LOW ;
: EYES-IN2-HIGH ( --) EYES-IN2-GPIO GPIO-HIGH ;
: EYES-IN2-LOW ( --) EYES-IN2-GPIO GPIO-LOW ;
: MOUTH-IN1-HIGH ( --) MOUTH-IN1-GPIO GPIO-HIGH ;
: MOUTH-IN1-LOW ( --) MOUTH-IN1-GPIO GPIO-LOW ;
: MOUTH-IN2-HIGH ( --) MOUTH-IN2-GPIO GPIO-HIGH ;
: MOUTH-IN2-LOW ( --) MOUTH-IN2-GPIO GPIO-LOW ;

( Henry Face Drive)
: EYES-COAST ( --) EYES-IN1-LOW EYES-IN2-LOW EYES-PWM-OFF ;
: MOUTH-COAST ( --)
  MOUTH-IN1-LOW MOUTH-IN2-LOW MOUTH-PWM-OFF
;
: FACE-DRIVE-IDLE ( --) EYES-COAST MOUTH-COAST ;
: EYES-OPEN-DRIVE ( --)
  TB6612-STBY-ON EYES-PWM-ON EYES-IN1-HIGH EYES-IN2-LOW
;
: EYES-CLOSE-DRIVE ( --)
  TB6612-STBY-ON EYES-PWM-ON EYES-IN1-LOW EYES-IN2-HIGH
;
: MOUTH-OPEN-DRIVE ( --)
  TB6612-STBY-ON MOUTH-PWM-ON MOUTH-IN1-HIGH MOUTH-IN2-LOW
;

( Henry Face Actions)
: MOUTH-CLOSE-DRIVE ( --)
  TB6612-STBY-ON MOUTH-PWM-ON MOUTH-IN1-LOW MOUTH-IN2-HIGH
;
: EYES-OPEN ( --)
  EYES-OPEN-DRIVE BLINK-RATE-MS @ MS-WAIT FACE-DRIVE-IDLE
;
: EYES-CLOSE ( --)
  EYES-CLOSE-DRIVE BLINK-RATE-MS @ MS-WAIT FACE-DRIVE-IDLE
;
: MOUTH-OPEN ( --)
  MOUTH-OPEN-DRIVE MOUTH-RATE-MS @ MS-WAIT FACE-DRIVE-IDLE
;
: MOUTH-CLOSE ( --)
  MOUTH-CLOSE-DRIVE MOUTH-RATE-MS @ MS-WAIT FACE-DRIVE-IDLE
;

( Henry Face Cycles)
: BLINK-ONCE ( --)
  EYES-CLOSE BLINK-DELAY-MS @ MS-WAIT
  EYES-OPEN BLINK-DELAY-MS @ MS-WAIT
;
: MOUTH-ONCE ( --)
  MOUTH-OPEN MOUTH-DELAY-MS @ MS-WAIT
  MOUTH-CLOSE MOUTH-DELAY-MS @ MS-WAIT
;
: FACE-RESET ( --)
  FACE-DRIVE-IDLE TB6612-STBY-ON
  EYES-OPEN MOUTH-CLOSE FACE-DRIVE-IDLE
;

( Henry Face Tests)
: BLINK ( N --) CLAMP0 0 ?DO BLINK-ONCE LOOP ;
: MOUTH ( N --) CLAMP0 0 ?DO MOUTH-ONCE LOOP ;
: FACE-OFF ( --) FACE-DRIVE-IDLE TB6612-STBY-OFF ;
: INIT-GPIO ( --)
  EYES-IN1-GPIO GPIO-OUT
  EYES-IN2-GPIO GPIO-OUT
  MOUTH-IN1-GPIO GPIO-OUT
  MOUTH-IN2-GPIO GPIO-OUT
  STBY-GPIO GPIO-OUT
  FACE-OFF
;
: TEST-BIT ( N --)
  DROP
  FACE-OFF
  TB6612-STBY-ON
;

( Example dry run)
( gforth tests/henry-face-motors-gforth.fs -e "INIT-GPIO 1 BLINK BYE")
